---
- name: Configurar IPv6 en Loopback 33
  hosts: csr1000v
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: ios
    ansible_user: admin
    ansible_password: cisco123

  tasks:
    - name: Crear interfaz Loopback 33 con IPv6
      ios_config:
        lines:
          - description "Configurada via Ansible"
          - ipv6 address 3001:ABCD:ABCD:1::1/128
          - ipv6 address FE80::1 link-local
        parents: interface Loopback33

    - name: Verificar configuración
      ios_command:
        commands:
          - show ipv6 interface Loopback33
      register: output

    - name: Mostrar resultado
      debug:
        var: output.stdout_lines